# site settings
title: In Memory of James Taylor
subtitle:
email:  jxtx.bio.memorial@gmail.com
description: The JHU Department of Biology and Graduate Program in Cell, Molecular, Developmental Biology and Biophysics remember James and his impact on our community.
baseurl: # the subpath of your site, e.g. /blog
url: https://jxtx-memorial.github.io # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country:
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 0

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman